function findTheDifference(s,t){
  s = s.split('').sort();
  t = t.split('').sort();
  for(let i = 0 ; i < t.length ; i++){
    if(s[i] !== t[i]){
      return t[i];
    }
  }
}

findTheDifference('abcd','abcde');

/* ==========================

Given two strings s and t which consist of only lowercase letters.

String t is generated by random shuffling string s and then add one more letter at a random position.

Find the letter that was added in t.

Example:

Input:
s = "abcd"
t = "abcde"

Output:
e

Explanation:
'e' is the letter that was added.

// i // str, str // str s and str t where t has an extra letter 
// o // str // our extra letter in t 
// c // ---
// e // ---

Strategy: 
We want to find the extra letter in t, we aren't sure of its' position
We can sort both strings and then iterate through our larger str
Once we hit a set of strings that are not equal we can return the letter in that does not belong

*/
